//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoMexicoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotos
    {
        public int id_foto { get; set; }
        public int lugar_id { get; set; }
        public string url_foto { get; set; }
        public string descripcion { get; set; }
    
        public virtual lugares lugares { get; set; }
    }
}
