//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoMexicoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Lugares
    {
        public int id_lugar { get; set; }
        public int categoria_id { get; set; }
        public string nombre_categoria { get; set; }
        public string nombre_lugar { get; set; }
        public string descripcion { get; set; }
        public string ubicacion { get; set; }
    }
}
